### ISSUE TITLE
Error line 35

### ISSUE THREAD

**Issue by amilopowers** [YBJazzer/GEBADR#2]
When I run the "GEBADR_OSMimport_script2_selection_to_import.py" script I get the following error:

```
[amilopowers@polarbaer ~]$ python3 '/home/amilopowers/Dokumente/OSM-GEBADR/GEBADR-master/GEBADR_OSMimport_script2_selection_to_import.py' 
Traceback (most recent call last):
  File "/home/amilopowers/Dokumente/OSM-GEBADR/GEBADR-master/GEBADR_OSMimport_script2_selection_to_import.py", line 35, in <module>
    latitude = [float(i) for i in latitude_strings]
  File "/home/amilopowers/Dokumente/OSM-GEBADR/GEBADR-master/GEBADR_OSMimport_script2_selection_to_import.py", line 35, in <listcomp>
    latitude = [float(i) for i in latitude_strings]
ValueError: could not convert string to float: 
[amilopowers@polarbaer ~]$ 
```
I attached my "GEBADR_selection" file for reference.
[GEBADR_selection.zip](https://github.com/YBJazzer/GEBADR/files/648466/GEBADR_selection.zip)

**Comment by YBJazzer** [comment]
Hi amilopowers,
sorry saw it a bit late, I will check on that.

**Comment by YBJazzer** [comment]
I found the error. Two remarks from my side:

1. The main problem is the last line. For some reason, your GEBADR_selection.csv contains a new last line: "Total Result,,,,,,,,,,,,"
If you delete this line, the script will work.

2. There are some entries "(empty)". Thereby, you will create OSM Tag descriptions "(empty)".

Can you somehow save the GEBADR_selection.csv in LibreOffice so that it does not create these "(empty)" entries and also does not create a new last line?

A suggestion from my side: 
Do you already see this "(empty)" entry and the last line when you open the GEBADR_OSMstyle_edited.csv in LibreOffice? But you don't see these entries when opening in a text editor?
Then make sure you import the GEBADR_OSMstyle_edited.csv into LibreOffice as text.
